[dev]
title = "ğŸ”§ PetConnect Dashboard"
background_color = "#d4edda"
text_color = "#155724"
header_color = "#28a745"
page_icon = "ğŸ¾"

[qa]
title = "ğŸ§ª PetConnect Dashboard"
background_color = "#fff3cd"
text_color = "#856404"
header_color = "#ffc107"
page_icon = "ğŸ¾"

[prod]
title = "ğŸš€ PetConnect Dashboard"
background_color="white"
text_color = "#721c24"
header_color = "#dc3545"
page_icon = "ğŸ¾"
secondaryBackgroundColor="lavender"
codeBackgroundColor="powderBlue"

[prod.sidebar]
background_color="ghostWhite"
secondaryBackgroundColor="lavender"